language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"
  # Download and install a specific Flash Player from the Adobe Archives:
  # http://helpx.adobe.com/flash-player/kb/archived-flash-player-versions.html
  - sh getFpFromArchive.sh 'http://download.macromedia.com/pub/flashplayer/installers/archive/fp_16.0.0.305_archive.zip'
  # add the Flash Player path to $PATH so that Java can find the Flash Player.  This is required by Flex-Mojos 4.x
  - export PATH="Flash Player Debugger.app/Contents/MacOS":$PATH
  # FLex-Mojo is expecting the "Flash Player" command so copy "Flash Player Debug" to "Flash Player"
  - cp Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player\ Debugger Flash\ Player\ Debugger.app/Contents/MacOS/Flash\ Player
  # Install FlexUnit 4.2 local
  - mvn install:install-file -Dfile='./libs/flexunit-4.2.0-20140410-as3_4.12.0.swc' -DgroupId='com.adobe.flexunit' -DartifactId='flexunit' -Dversion='4.2.0-20140410' -Dpackaging=swc
  # Install Hamcrest local
  - mvn install:install-file -Dfile='./libs/hamcrest-as3-flex-1.1.3.swc' -DgroupId='org.hamcrest' -DartifactId='hamcrest-as3' -Dversion='1.1.3' -Dpackaging=swc -Dclassifier=flex
  # Install mockolate local
  - mvn install:install-file -Dfile='./libs/mockolate-0.12.4-flex.swc' -Dversion='0.12.4' -Dclassifier=flex -Dpackaging=swc -DgroupId=mockolate -DartifactId=mockolate

script: mvn test
